server:
  port: 8765
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customers-microservice
          uri: http://localhost:8080/
          predicates:
            - Path=/customers/**